// <auto-generated />
using System;
using Listen2MeRefined.Infrastructure.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listen2MeRefined.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Listen2MeRefined.Infrastructure.Data.Models.AudioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<short>("BPM")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("TEXT");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Listen2MeRefined.Infrastructure.Data.Models.MusicFolderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeSubdirectories")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppSettingsId");

                    b.ToTable("MusicFolders");
                });

            modelBuilder.Entity("Listen2MeRefined.Infrastructure.Data.Models.PlaylistModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Listen2MeRefined.Infrastructure.Settings.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioOutputDeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoCheckUpdatesOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoScanOnFolderAdd")
                        .HasColumnType("INTEGER");

                    b.Property<short>("CornerTriggerDebounceMs")
                        .HasColumnType("INTEGER");

                    b.Property<short>("CornerTriggerSizePx")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableCornerNowPlayingPopup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableGlobalMediaKeys")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FolderBrowserStartAtLastLocation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastBrowsedFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MutedDroppedSongFoldersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewSongWindowPosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedFoldersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanMilestoneBasis")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ScanMilestoneInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScanOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchResultsTransferMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowScanMilestoneCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTaskPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartMuted")
                        .HasColumnType("INTEGER");

                    b.Property<float>("StartupVolume")
                        .HasColumnType("REAL");

                    b.Property<short>("TaskPercentageReportInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseCompactPlaylistView")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PlaylistSongs", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistSongs", (string)null);
                });

            modelBuilder.Entity("Listen2MeRefined.Infrastructure.Data.Models.MusicFolderModel", b =>
                {
                    b.HasOne("Listen2MeRefined.Infrastructure.Settings.AppSettings", null)
                        .WithMany("MusicFolders")
                        .HasForeignKey("AppSettingsId");
                });

            modelBuilder.Entity("PlaylistSongs", b =>
                {
                    b.HasOne("Listen2MeRefined.Infrastructure.Data.Models.PlaylistModel", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listen2MeRefined.Infrastructure.Data.Models.AudioModel", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Listen2MeRefined.Infrastructure.Settings.AppSettings", b =>
                {
                    b.Navigation("MusicFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
