global using Listen2MeRefined.Core.Interfaces;
global using Listen2MeRefined.Core.Models;
global using Listen2MeRefined.Core.Enums;
global using Listen2MeRefined.Core.Interfaces.DataHandlers;
global using Listen2MeRefined.Core;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Serilog;
global using System.Collections.Generic;
global using System.Data;
global using System.Threading.Tasks;
global using IDataReader = Listen2MeRefined.Core.Interfaces.DataHandlers.IDataReader;